### Register a new user
POST http://localhost:3000/register
Content-Type: application/json

{
  "name": "edwin",
  "email": "frida2@example.com",
  "password": "123456"
}

###

### Login with the registered user
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
  "email": "frida2@example.com",
  "password": "123456"
}

### send file
POST http://localhost:3000/file
Content-Type: multipart/form-data

name=frida2
file=@/home/atia/Documentos/1.png

