### Register a new user
POST http://localhost:3000/register
Content-Type: application/json

{
  "name": "aurora",
  "email": "aurora@example.com",
  "password": "123456"
}

### Login with the registered user
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
  "email": "aurora@example.com",
  "password": "123456"
}

### Get all files of a user
GET http://localhost:3000/files?name=edwin
Content-Type: application/json


### Get a file
GET http://localhost:3000/file
Content-Type: application/json

{
  "user_id": 1,
  "fileName": "5.jpg"
}